apiVersion: 1

datasources:
  # Prometheus
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  # InfluxDB
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: energy-data
    user: admin
    secureJsonData:
      password: tuya123
    jsonData:
      version: Flux
      organization: tuya-org
      defaultBucket: energy-data
      tlsSkipVerify: true

  # MongoDB (via Grafana MongoDB plugin)
  - name: MongoDB
    type: grafana-mongodb-datasource
    access: proxy
    url: http://mongodb:27017
    database: tuya
    user: admin
    secureJsonData:
      password: tuya123
    jsonData:
      authType: basic
      tlsSkipVerify: true

  # PostgreSQL
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: tuya_alt
    user: tuya_user
    secureJsonData:
      password: tuya123
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAutoIdle: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
